
on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        env: 
         CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          creds: ${{ env.CREDENTIALS }}

          